### ISSUE TITLE
web3.exceptions.InvalidAddress, When running make child-chain

### ISSUE THREAD

**Issue by devonwesley** [omisego/plasma-mvp#150]
<img width="836" alt="screen shot 2018-07-11 at 3 38 00 pm" src="https://user-images.githubusercontent.com/8162708/42575380-9c7640ae-8520-11e8-8553-d4172e9ea179.png">

## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
- When running `make child-chain` I get the error pictured above. It tells me the address is invalid but it looks valid to me. Its the address of the `root-chain` contract. `0xa3b2a1804203b75b494028966c0f62e677447a39`

## Expected Behavior
I was following the readme, so I expected the `child-chain` server to start up.

## Steps to Reproduce

1. Follow readme steps
2. Then run `make child-chain`

## Motivation for Change
I would just like help so I can continue.

## System Specs

- python version: `3.6.6`
- pyetherem version: `none`
- environment (output of running `pip freeze`):
```
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
cytoolz==0.9.0.1
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
ethereum==2.3.0
flake8==3.5.0
future==0.16.0
hexbytes==0.1.0
idna==2.7
json-rpc==1.10.8
lru-dict==1.1.6
mccabe==0.6.1
more-itertools==4.2.0
parsimonious==0.8.0
pbkdf2==1.3
plasma==0.0.0
pluggy==0.6.0
plyvel==1.0.4
py==1.5.4
py-ecc==1.4.3
py-solc==3.1.0
pycodestyle==2.3.1
pycryptodome==3.6.4
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.6.3
PyYAML==4.2b4
repoze.lru==0.7
requests==2.19.1
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.23
web3==4.3.0
websockets==4.0.1
Werkzeug==0.13
```
- operating system: `MacOS High Sierra`

**Comment by kfichter** [comment]
Thanks for the report! I've submitted a patch here: #151 

The root of this issue was here:
https://github.com/omisego/plasma-mvp/blob/595b7e85c8050ba02365df14fdce552ff5dc38f1/plasma/config.py#L2

Web3py is strict about address checksums (for good reason) as of v4. I updated the address to a correctly formatted address.

**Comment by devonwesley** [comment]
Nice Thank you so much. @kfichter 

I'll give it a shot and see how it works.

**Comment by devonwesley** [comment]
Nice, it worked! Thanks

**Comment by bh2smith** [comment]
Please notice that the demo/example commands also contain BAD-dresses! For example;

`omg deposit 100 0xfd02ecee62797e75d86bcff1642eb0844afb28c7`

Also yields, **web3.exceptions.InvalidAddress**

**Comment by devonwesley** [comment]
Yeah you can fix it by using the checksum: `Web3.toChecksumAddress(ADDRESS)`

Inside of the client.py file. @bh2smith

**Comment by kfichter** [comment]
Will try to update the patch today

**Comment by hernandp** [comment]
@kfichter  I dont want to reopen this, but *deposit* command with latest code throws the same error...

**Comment by kfichter** [comment]
@hernandp What command are you using and what's the error?

**Comment by hernandp** [comment]
@kfichter  

```
:plasma-mvp ck$ omg deposit 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7
Traceback (most recent call last):
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/bin/omg", line 11, in <module>
    load_entry_point('plasma==0.0.0', 'console_scripts', 'omg')()
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/cli/cli.py", line 18, in cli
    ctx.obj = Client()
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/client/client.py", line 16, in __init__
    self.root_chain = deployer.get_contract_at_address("RootChain", plasma_config['ROOT_CHAIN_CONTRACT_ADDRESS'], concise=True)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/root_chain/deployer.py", line 150, in get_contract_at_address
    contract_instance = self.w3.eth.contract(abi=abi, address=address)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/web3/eth.py", line 369, in contract
    return ContractFactory(address)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/web3/contract.py", line 240, in __init__
    self.address = normalize_address(self.web3.ens, address)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/web3/utils/normalizers.py", line 160, in normalize_address
    validate_address(address)
  File "/Users/coinfabrik/.pyenv/versions/3.6.6rc1/lib/python3.6/site-packages/web3/utils/validation.py", line 157, in validate_address
    value,
web3.exceptions.InvalidAddress: ('Web3.py only accepts checksum addresses. The software that gave you this non-checksum address should be considered unsafe, please file it as a bug on their platform. Try using an ENS name instead. Or, if you must accept lower safety, use Web3.toChecksumAddress(lower_case_address).', '0xa3b2a1804203b75b494028966c0f62e677447a39')
```
