### ISSUE TITLE
where is plasma.config?

### ISSUE THREAD

**Issue by hot3246624** [omisego/plasma-mvp#156]
when i excuted omg xxx, there is an error: ModuleNotFoundError: No module named 'plasma.config'

the detail is:
Traceback (most recent call last):
  File "/Users/huangzhiyong/anaconda3/bin/omg", line 11, in <module>
    load_entry_point('plasma==0.0.0', 'console_scripts', 'omg')()
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2691, in load_entry_point
    return ep.load()
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/cli/__init__.py", line 1, in <module>
    from .cli import cli  # Noqa F401
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/cli/cli.py", line 6, in <module>
    from plasma.client.client import Client
  File "/Users/huangzhiyong/anaconda3/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/client/client.py", line 7, in <module>
    from plasma.config import plasma_config
ModuleNotFoundError: No module named 'plasma.config'

**Comment by kfichter** [comment]
Hey! Thanks for the bug report. I've gone ahead and submitted a PR that I believe fixes the issue.
