### ISSUE TITLE
Tests don't work on OSX and python 3.6/3.7

### ISSUE THREAD

**Issue by PaulRBerg** [omisego/plasma-mvp#167]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

Tests do not run on python 3.7. I also tried to run the source code on `3.4.0` and `3.4.8`, but I couldn't even pass by `make`.

## Expected Behavior

Test should run with python 3.7, as in the README it specifies "python 3.2+".

## Steps to Reproduce

1. git clone git@github.com:omisego/plasma-mvp.git
2. make
3. make test

Full output of error:
```
Traceback (most recent call last):
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytest-3.7.1-py3.7.egg/_pytest/config/__init__.py", line 372, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/Users/paulrberg/Documents/DLT/eth/plasma/plasma-mvp/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytest-3.7.1-py3.7.egg/_pytest/config/__init__.py", line 403, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/Users/paulrberg/Documents/DLT/eth/plasma/plasma-mvp/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytest-3.7.1-py3.7.egg/_pytest/config/__init__.py", line 409, in _importconftest
    mod = conftestpath.pyimport()
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py-1.5.4-py3.7.egg/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pytest-3.7.1-py3.7.egg/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/Users/paulrberg/Documents/DLT/eth/plasma/plasma-mvp/tests/conftest.py", line 7, in <module>
    from plasma.root_chain.deployer import Deployer
  File "/Users/paulrberg/Documents/DLT/eth/plasma/plasma-mvp/plasma/root_chain/deployer.py", line 4, in <module>
    from web3.contract import ConciseContract
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/web3-4.3.0-py3.7.egg/web3/__init__.py", line 8, in <module>
    from web3.main import Web3  # noqa: E402
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/web3-4.3.0-py3.7.egg/web3/main.py", line 26, in <module>
    from web3.providers.eth_tester import (
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/web3-4.3.0-py3.7.egg/web3/providers/__init__.py", line 8, in <module>
    from .websocket import WebsocketProvider  # noqa: F401
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/web3-4.3.0-py3.7.egg/web3/providers/websocket.py", line 9, in <module>
    import websockets
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/websockets-4.0.1-py3.7-macosx-10.13-x86_64.egg/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/websockets-4.0.1-py3.7-macosx-10.13-x86_64.egg/websockets/client.py", line 20, in <module>
    from .protocol import WebSocketCommonProtocol
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/websockets-4.0.1-py3.7-macosx-10.13-x86_64.egg/websockets/protocol.py", line 18, in <module>
    from .compatibility import asyncio_ensure_future
  File "/Users/paulrberg/.pyenv/versions/3.7.0/lib/python3.7/site-packages/websockets-4.0.1-py3.7-macosx-10.13-x86_64.egg/websockets/compatibility.py", line 15
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
ERROR: could not load /Users/paulrberg/Documents/DLT/eth/plasma/plasma-mvp/tests/conftest.py
```

Notice this line:
```
asyncio_ensure_future = asyncio.async           # Python < 3.5
```

## System Specs

- operating system: osx high sierra 10.13.5
- python version: 3.7
- virtualenv: 16.0.0
- pyetherem version: 2.3.0
- environment (output of running `pip freeze`):
```
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
cytoolz==0.9.0.1
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.4
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-utils==1.0.3
ethereum==2.3.0
flake8==3.5.0
future==0.16.0
hexbytes==0.1.0
idna==2.7
json-rpc==1.10.8
lru-dict==1.1.6
mccabe==0.6.1
more-itertools==4.3.0
parsimonious==0.8.0
pbkdf2==1.3
plasma==0.0.0
pluggy==0.7.1
plyvel==1.0.4
py==1.5.4
py-ecc==1.4.3
py-solc==3.1.0
pycodestyle==2.3.1
pycryptodome==3.6.4
pyethash==0.1.27
pyflakes==1.6.0
pysha3==1.0.2
pytest==3.7.1
PyYAML==4.2b4
repoze.lru==0.7
requests==2.19.1
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.23
web3==4.3.0
websockets==4.0.1
Werkzeug==0.13
```

**Comment by PaulRBerg** [comment]
Switched to 3.6, now I get `11 failed, 28 passed`.

**Comment by kfichter** [comment]
Unfortunately the fix for now is to use py3.6 :-/ Need to figure out a better solution. Will make a new issue to support py3.7 and update README to let users know to use 3.6.
