### ISSUE TITLE
[bug]Could not identify the intended function with name `startDepositExit`

### ISSUE THREAD

**Issue by KvApril** [omisego/plasma-mvp#168]
## Issue Type 

[x] bug report

```
[ ] bug report
```

## Current Behavior

when call 
```
omg withdrawdeposit 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7 1 100
```
the error
```
Could not identify the intended function with name `startDepositExit`, 
```

## Expected Behavior

expect get correct response
```
Submitted withdrawal

```

## Steps to Reproduce

1. Follow readme to have software running as intended
2.  execute command for withdrawdeposit  (as in sample)

- Full output of error:
```
Traceback (most recent call last):
  File "/home/alex/soft/sidechain/env/bin/omg", line 11, in <module>
    load_entry_point('plasma==0.0.0', 'console_scripts', 'omg')()
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/plasma-0.0.0-py3.5.egg/plasma/cli/cli.py", line 157, in withdrawdeposit
    client.withdraw_deposit(owner, deposit_pos, amount)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/plasma-0.0.0-py3.5.egg/plasma/client/client.py", line 53, in withdraw_deposit
    self.root_chain.startDepositExit(deposit_pos, amount, transact={'from': owner})
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/web3-4.3.0-py3.5.egg/web3/contract.py", line 879, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/web3-4.3.0-py3.5.egg/web3/contract.py", line 892, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/web3-4.3.0-py3.5.egg/web3/contract.py", line 1025, in __call__
    clone._set_function_info()
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/web3-4.3.0-py3.5.egg/web3/contract.py", line 1034, in _set_function_info
    self.kwargs
  File "/home/alex/soft/sidechain/env/lib/python3.5/site-packages/web3-4.3.0-py3.5.egg/web3/utils/contracts.py", line 128, in find_matching_fn_abi
    raise ValidationError(message)
web3.exceptions.ValidationError: 
Could not identify the intended function with name `startDepositExit`, positional argument(s) of type `(<class 'int'>, <class 'int'>)` and keyword argument(s) of type `{}`.
Found 1 function(s) with the name `startDepositExit`: ['startDepositExit(uint256,address,uint256)']
Function invocation failed due to improper number of arguments.

```
- Code that caused error:
```
  def withdraw_deposit(self, owner, deposit_pos, amount):
      self.root_chain.startDepositExit(deposit_pos, amount, transact={'from': owner})
```

## Suggested Fix

the withdraw_deposit need one more param.....
```
def withdraw_deposit(self, owner, deposit_pos,amount,token='0x0.....0'):
        self.root_chain.startDepositExit(deposit_pos,token,amount, transact={'from': owner})
```

## System Specs

- python version: ```3.5.2```
- pyetherem version: ```2.3.0```
- environment (output of running `pip freeze`):
```
atomicwrites==1.1.5
attrdict==2.0.0
attrs==18.1.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
cytoolz==0.9.0.1
eth-abi==1.1.1
eth-account==0.2.3
eth-hash==0.1.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-rlp==0.1.2
eth-tester==0.1.0b15
eth-utils==1.0.3
ethereum==2.3.0
flake8==3.5.0
future==0.16.0
hexbytes==0.1.0
idna==2.7
json-rpc==1.10.8
leveldb==0.194
lru-dict==1.1.6
mccabe==0.6.1
more-itertools==4.2.0
parsimonious==0.8.0
pbkdf2==1.3
plasma==0.0.0
pluggy==0.6.0
plyvel==1.0.4
py==1.5.4
py-ecc==1.4.3
py-solc==3.1.0
pycodestyle==2.3.1
pycryptodome==3.6.3
pyethash==0.1.27
pyflakes==1.6.0
pylru==1.1.0
pysha3==1.0.2
pytest==3.6.2
PyYAML==3.12
repoze.lru==0.7
requests==2.19.1
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.23
web3==4.3.0
websockets==4.0.1
Werkzeug==0.13
```
- operating system: ```ubuntu```

**Comment by kfichter** [comment]
Hi, can you confirm that this is now fixed as per #175?

**Comment by KvApril** [comment]
@kfichter  yes,It has been fixed.
Another question that I didn't mention it in my email.
you also need to modify the example about send_tx : 
`send_tx 1 0 0 0 0 0 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7 50 0x4B3eC6c9dC67079E82152d6D55d8dd96a8e6AA26 45 5 3bb369fecdc16b93b99514d8ed9c2e87c5824cf4a6a98d2e8e91b7dd0c063304`

**Comment by KvApril** [comment]
@kfichter Hi,sorry to bother you.  can you check your gmail and give me a reply?　Thank you so much!
