### ISSUE TITLE
cannot run omg deposit

### ISSUE THREAD

**Issue by victoryeo** [omisego/plasma-mvp#210]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

When i do omg deposit 100 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7, there is an error:

ValueError: {'message': 'Attempting to run transaction which calls a contract function, but recipient address 0xA3B2a1804203b75b494028966C0f62e677447A39 is not a contract address', 'code': -32000, 'data': {'stack': 'r: Attempting to run transaction which calls a contract function, but recipient address 0xA3B2a1804203b75b494028966C0f62e677447A39 is not a contract address\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:77112\n

## Expected Behavior

Please tell us how to get root contract address

## Steps to Reproduce

1. make child-chain
2. omg deposit 100 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7

- Full output of error:
Traceback (most recent call last):
  File "/usr/local/bin/omg", line 11, in <module>
    load_entry_point('plasma==0.0.0', 'console_scripts', 'omg')()
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/cli/cli.py", line 38, in deposit
    client.deposit(amount, address)
  File "/usr/local/lib/python3.6/site-packages/plasma-0.0.0-py3.6.egg/plasma/client/client.py", line 41, in deposit
    self.root_chain.deposit(transact={'from': owner, 'value': amount})
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/contract.py", line 879, in __call__
    return self.__prepared_function(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/contract.py", line 892, in __prepared_function
    return getattr(self._function(*args), modifier)(modifier_dict)
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/contract.py", line 1142, in transact
    **self.kwargs
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/contract.py", line 1438, in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/eth.py", line 263, in sendTransaction
    get_buffered_gas_estimate(self.web3, transaction),
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/utils/transactions.py", line 84, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/eth.py", line 304, in estimateGas
    [transaction],
  File "/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/manager.py", line 110, in request_blocking
    raise ValueError(response["error"])
ValueError: {'message': 'Attempting to run transaction which calls a contract function, but recipient address 0xA3B2a1804203b75b494028966C0f62e677447A39 is not a contract address', 'code': -32000, 'data': {'stack': 'r: Attempting to run transaction which calls a contract function, but recipient address 0xA3B2a1804203b75b494028966C0f62e677447A39 is not a contract address\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:77112\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:67771\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:30:126629\n    at e.exports.i.getCode (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:2:123698)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:30:126579\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:50739\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54500\n    at Object.return (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54077)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:52329\n    at e (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54448)\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:54431\n    at /usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:51541\n    at process.internalTickCallback (internal/process/next_tick.js:70:11)', 'name': 'r'}}

- Command that caused error:
omg deposit 100 0xfd02EcEE62797e75D86BCff1642EB0844afB28c7
- Code that caused error:
no code

## Motivation for Change

could not use the plasma mvp 

## System Specs

macbook pro

- python version: 2.6.5
- pyetherem version: no
- environment (output of running `pip freeze`):
- operating system: mac os high sierra

**Comment by victoryeo** [comment]
the solutions is:
after you deploy the root chain contract, using make root-chain, you have to copy the root chain contract address, to the file plasma_core/constants.py, to the field 
CONTRACT_ADDRESS = '<contract_address>'
