### ISSUE TITLE
make test failure

### ISSUE THREAD

**Issue by victoryeo** [omisego/plasma-mvp#211]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

when running make test, test_child_chain.py:11 fails

## Expected Behavior

the test should pass

## Steps to Reproduce

1. make test

- Full output of error:
========================================================== FAILURES ===========================================================
_____________________________________________________ test_apply_deposit ______________________________________________________

test_lang = <testlang.testing_language.TestingLanguage object at 0x105408ef0>

    def test_apply_deposit(test_lang):
        owner = test_lang.get_account()
        amount = 100
    
>       test_lang.deposit(owner, amount)

tests/child_chain/test_child_chain.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
testlang/testing_language.py:28: in deposit
    'value': amount
/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/contract.py:1438: in transact_with_contract_function
    txn_hash = web3.eth.sendTransaction(transact_transaction)
/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/eth.py:268: in sendTransaction
    [transaction],
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <web3.manager.RequestManager object at 0x1054086a0>, method = 'eth_sendTransaction'
params = [{'data': '0xd0e30db0', 'from': '0x4B3eC6c9dC67079E82152d6D55d8dd96a8e6AA26', 'gas': 170907, 'to': '0xFC628dd79137395F3C9744e33b1c5DE554D94882', ...}]

    def request_blocking(self, method, params):
        """
        Make a synchronous request using the provider
        """
        response = self._make_request(method, params)
    
        if "error" in response:
>           raise ValueError(response["error"])
E           ValueError: {'message': 'sender account not recognized', 'code': -32000, 'data': {'stack': 'r: sender account not recognized\n    at StateManager.queueTransaction (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:68721)\n    at s.eth_sendTransaction (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:81687)\n    at s.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:78847)\n    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225418)\n    at c.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:85837)\n    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225418)\n    at o.d.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:90270)\n    at o.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:97049)\n    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225418)\n    at f.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:86274)\n    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225418)\n    at c.handleRequest (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:87427)\n    at a (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225418)\n    at s._handleAsync (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:225454)\n    at Timeout._onTimeout (/usr/local/lib/node_modules/ganache-cli/build/cli.node.js:149:224879)\n    at listOnTimeout (timers.js:324:15)\n    at processTimers (timers.js:268:5)', 'name': 'r'}}

/usr/local/lib/python3.6/site-packages/web3-4.5.0-py3.6.egg/web3/manager.py:110: ValueError

- Command that caused error:
make test

- Code that caused error:
tests/child_chain/test_child_chain.py:11

## Motivation for Change

plasma mvp cannot be run

## System Specs

- python version: 3.6.5
- pyetherem version: n/a
- environment (output of running `pip freeze`): 
- operating system: mac os high sierrs

**Comment by kasima** [comment]
@victoryeo – Thank you for reporting the issue. We're not actively maintaining this repo to focus on implementation that's happening over in [plasma-contracts](https://github.com/omisego/plasma-contracts) and [elixir-omg](https://github.com/omisego/elixir-omg). I'm not sure when we'll come back to this. However, PRs are still welcome, if this is something you'd like to dig into!
