### ISSUE TITLE
Deployment Error: `ImportError: cannot import name 'force_text'`

### ISSUE THREAD

**Issue by fredfortier** [omisego/plasma-mvp#40]
I'm getting an `ImportError: cannot import name 'force_text'` when trying to `make root-chain` after pulling from master today. I started fresh and ran `make`. I'll continue troubleshooting but I'd appreciate any hint if anyone run into the same issue or if I'm just missing something obvious.
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.20+commit.3155dd80.Darwin.appleclang
```
```
Frederics-MacBook-Pro:~ fredfortier$ ganache-cli -m=plasma_mvp
Ganache CLI v6.0.3 (ganache-core: 2.0.2)
```
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ pip freeze
attrs==17.4.0
certifi==2018.1.18
chardet==3.0.4
click==6.7
cytoolz==0.9.0
eth-abi==1.0.0
eth-hash==0.1.0
eth-keyfile==0.5.1
eth-keys==0.2.0b3
eth-tester==0.1.0b21
eth-utils==1.0.1
ethereum==2.3.0
future==0.16.0
idna==2.6
json-rpc==1.10.8
pbkdf2==1.3
plasma==0.0.0
pluggy==0.6.0
plyvel==1.0.4
py==1.5.2
py-ecc==1.4.2
py-solc==2.1.0
pycryptodome==3.4.11
pyethash==0.1.27
pylru==1.0.9
pysha3==1.0.2
pytest==3.4.1
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.22
web3==3.16.4
Werkzeug==0.13
```
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ python --version
Python 3.6.4
```
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ make root-chain
python deployment.py
Traceback (most recent call last):
  File "deployment.py", line 1, in <module>
    from plasma.root_chain.deployer import Deployer
  File "/Users/fredfortier/Code/sandbox/plasma-mvp/plasma/root_chain/deployer.py", line 2, in <module>
    import web3
  File "/Users/fredfortier/Code/sandbox/plasma-mvp/python3/lib/python3.6/site-packages/web3-3.16.4-py3.6.egg/web3/__init__.py", line 5, in <module>
    from web3.main import Web3
  File "/Users/fredfortier/Code/sandbox/plasma-mvp/python3/lib/python3.6/site-packages/web3-3.16.4-py3.6.egg/web3/main.py", line 6, in <module>
    from eth_utils import (
ImportError: cannot import name 'force_text'
make: *** [root-chain] Error 1
```

**Comment by snegishi** [comment]
You need to install eth-utils(0.8.1) because 'force_text' is removed at the latest version.
```pip install eth-utils==0.8.1```

**Comment by bun919tw** [comment]
You need to downgrade some packages version.
```
eth-abi (0.5.0)
eth-hash (0.1.0)
eth-keyfile (0.4.1)
eth-keys (0.1.0b4)
eth-tester (0.1.0b15)
eth-utils (0.7.3)
```
The above versions work with me.

**Comment by fredfortier** [comment]
This it worked. I also had to downgrade Solidity to 0.4.18. Here is the command:
```
brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/2aea171d7d6901b97d5f1f71bd07dd88ed5dfb42/solidity.rb
```

Here are my exact requirements:
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ pip freeze
attrs==17.4.0
certifi==2018.1.18
chardet==3.0.4
click==6.7
cytoolz==0.9.0
eth-abi==0.5.0
eth-hash==0.1.0
eth-keyfile==0.4.1
eth-keys==0.1.0b4
eth-tester==0.1.0b15
eth-utils==0.7.3
ethereum==2.3.0
future==0.16.0
idna==2.6
json-rpc==1.10.8
pbkdf2==1.3
plasma==0.0.0
pluggy==0.6.0
plyvel==1.0.4
py==1.5.2
py-ecc==1.4.2
py-solc==2.1.0
pycryptodome==3.4.11
pyethash==0.1.27
pylru==1.0.9
pysha3==1.0.2
pytest==3.4.1
PyYAML==3.12
repoze.lru==0.7
requests==2.18.4
rlp==0.6.0
scrypt==0.8.6
semantic-version==2.6.0
six==1.11.0
toolz==0.9.0
urllib3==1.22
web3==3.16.4
Werkzeug==0.13
```
```
(python3) Frederics-MacBook-Pro:plasma-mvp fredfortier$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.18+commit.9cf6e910.Darwin.appleclang
```

**Comment by fredfortier** [comment]
Naive attempt to run the program was unsuccessful but I was able to work around the issue as described above.
